### ISSUE TITLE
Add delta time to fx.update

### ISSUE THREAD

**Issue by rin3s** [bma73/revolt-fx#1]
Revolt FX is looknig nice, we're loving it and going to try it out. 👍 

As a developer, it would be nice if we could have delta time as a parameter in the update function.
This is to take into consideration the PIXI.ticker.shared.speed variable.

We did this quick test to see that it works out.
`  
FX.prototype.update = function (delta) {
        if (!this.active)
            return;
        var t = Date.now();
        var dt = delta;
        if (delta === undefined) {
          dt = (t - this._timeElapsed);
        }
        dt *= 0.001;
        var list = this._effects;
        var node = list.first;
        var next;
        while (node) {
            next = node.next;
            node.update(dt);
            node = next;
        }
        this._timeElapsed = t;
    };
`

**Comment by bma73** [comment]
Good point! I've added support for delta time 
(f8d8e7fd16452e38c6b6a2aa8e6d480546f82fdf)
