### ISSUE TITLE
tested and this component is not loaded.

### ISSUE THREAD

**Issue by jjhesk** [bma73/revolt-fx#3]
error" Settings not defined for 'fx-shield01'

**Comment by jjhesk** [comment]
now using pixi v5

**Comment by digiur** [comment]
Were you able to get this working for pixi v5?

**Comment by bma73** [comment]
It's on my todo list :-) ... I already had a quick look, but it seems that there would be some more time needed to update it

**Comment by bma73** [comment]
@jjhesk @digiur Just updated to work with Pixi V5...

**Comment by phamtrantriem** [comment]
> error" Settings not defined for 'fx-shield01'

how did you fix that? i'm getting that error right now at the lastest version.
