### ISSUE TITLE
Start ParticleEmitter after stop but before all particles finished leads to no start

### ISSUE THREAD

**Issue by Puuca** [bma73/revolt-fx#7]
The issue is, when we have a ParticleEmitter with long-lasting particles (like Snow) and stop it, (with waitingForParticles=true) the particles stop spawning but until the last particle is gone it is still active. when we start the emitter again while it is still active, the start function get completely skipped. I tried myself a bit around and found out.
When we change the first line of the ParticleEmitter start function from
`if(this._active)
    return;`

to
`if(this.active){
    this._exhausted=false;
    return;
}`

The particle emitter continues without any issues.

If you say "No, this is wanted" then its Ok, its more a Suggestion.

**Comment by bma73** [comment]
Hey,
it's been quite a while ago, since you added your suggestion :-)
Could you just try to set  .isExhausted = false ?
